# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: build and test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: List directories for debugging
      run: |
        echo "Current directory:"
        pwd
        echo "Listing all files recursively:"
        ls -R

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x 

    - name: Restore dependencies
      run: dotnet restore ./UniversityAdmission/UniversityAdmission.sln
    - name: Build
      run: dotnet build ./UniversityAdmission/UniversityAdmission.sln --no-restore
    - name: Test
      run: dotnet test ./UniversityAdmission/UniversityAdmission.sln --no-build --verbosity normal
